name: Monitor MIBGAS Alfaenergia

on:
  schedule:
    # MODO SPAM: Tenta correr de 2 em 2 minutos, a qualquer hora do dia
    - cron: '*/2 * * * *'
  workflow_dispatch: # Mantém o botão ativo por segurança

permissions:
  contents: write  # Dá permissão obrigatória de escrita ao token

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar o Código para o Servidor
      uses: actions/checkout@v4

    - name: Configurar o Python no Servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependências necessárias
      run: pip install requests

    - name: Executar o Script Automatizado
      env:
        TEU_EMAIL: ${{ secrets.TEU_EMAIL }}
        TUA_SENHA_APP: ${{ secrets.TUA_SENHA_APP }}
      run: python alfaprojeto.py

    - name: Guardar Histórico Atualizado na Nuvem
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "💾 Estado de preços atualizado [Bot]"
        file_pattern: 'historico_precos.json'
